<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="office-desktop" duration-ms="1067" started-at="2015-03-15T07:25:49Z" finished-at="2015-03-15T07:25:50Z">
    <groups>
    </groups>
    <test name="Utilities Package Test" duration-ms="1067" started-at="2015-03-15T07:25:49Z" finished-at="2015-03-15T07:25:50Z">
      <class name="rc.qaportal.web.automation.aramark.utilities.SuperUserLoginUtilityTest">
        <test-method status="PASS" signature="dev2_super_user_credentials()[pri:0, instance:rc.qaportal.web.automation.aramark.utilities.SuperUserLoginUtilityTest@1bbe5e8]" name="dev2_super_user_credentials" duration-ms="80" started-at="2015-03-15T12:25:49Z" finished-at="2015-03-15T12:25:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dev2_super_user_credentials -->
        <test-method status="FAIL" signature="login_super_dev2()[pri:0, instance:rc.qaportal.web.automation.aramark.utilities.SuperUserLoginUtilityTest@1bbe5e8]" name="login_super_dev2" duration-ms="908" started-at="2015-03-15T12:25:50Z" finished-at="2015-03-15T12:25:50Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at rc.qaportal.web.automation.aramark.utilities.UserLoginUtility.loginToAramarkPortal(UserLoginUtility.java:16)
	at rc.qaportal.web.automation.aramark.utilities.SuperUserLoginUtility.loginAsSuperUser(SuperUserLoginUtility.java:18)
	at rc.qaportal.web.automation.aramark.utilities.SuperUserLoginUtilityTest.login_super_dev2(SuperUserLoginUtilityTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_super_dev2 -->
      </class> <!-- rc.qaportal.web.automation.aramark.utilities.SuperUserLoginUtilityTest -->
    </test> <!-- Utilities Package Test -->
  </suite> <!-- office-desktop -->
</testng-results>
