<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ubuntu" name="com.rc.wefunit.TestClassInstantiationUtilityTest" tests="1" failures="1" timestamp="2 Apr 2015 10:55:53 GMT" time="0.011" errors="0">
  <testcase name="instantiate_subclass_of_GenericServiceOperationTest_serviceOperationName_1" time="0.011" classname="com.rc.wefunit.TestClassInstantiationUtilityTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1
	at com.rc.wefunit.DefaultTestClassInstantiationUtility.instantiateTestClass(DefaultTestClassInstantiationUtility.java:22)
	at com.rc.wefunit.TestClassInstantiationUtilityTest.instantiate_subclass_of_GenericServiceOperationTest_serviceOperationName_1(TestClassInstantiationUtilityTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- instantiate_subclass_of_GenericServiceOperationTest_serviceOperationName_1 -->
</testsuite> <!-- com.rc.wefunit.TestClassInstantiationUtilityTest -->
